### ISSUE TITLE
webtrees 2.1.1

### ISSUE THREAD

**Issue by Poyet01** [jchue/argon-webtrees-theme#10]
Bonjour,
Avez-vous prévu une adaptation du thème Argon à la version 2.1.1 de webtrees ? Car je vous l'avoue j'utilisais principalement votre thème car plus clair.
Dans l'attente de vous lire, bien cordialement.
------------------------------------
Google translate
------------------------------------
Hello,
Have you planned an adaptation of the Argon theme to version 2.1.1 of webtrees? Because I confess I mainly used your theme because it was clearer.
Looking forward to hearing from you, best regards.

**Comment by jchue** [comment]
Hi. Yes, thank you for letting me know! Give me a week or so to work on this. I need to update a few other things as well.

---

Salut. Oui, merci de me l'avoir signalé ! Donnez-moi environ une semaine pour travailler dessus. J'ai besoin de mettre à jour quelques autres choses aussi.

**Comment by Poyet01** [comment]
Bonjour,
Vous avez pu avancer ?
Bonne journée
-------------------------------------------
Google translate
-----------------------------------------
Hello,
Were you able to move on?
Have a good day

**Comment by jchue** [comment]
I've just released [v2.0.0](https://github.com/jchue/argon-webtrees-theme/releases/tag/v2.0.0). There are quite drastic stylistic changes, but I hope you like them. Please try it and let me know if you find any bugs. Thank you for your patience!

---

Je viens de sortir la [v2.0.0](https://github.com/jchue/argon-webtrees-theme/releases/tag/v2.0.0). Il y a des changements stylistiques assez drastiques, mais j'espère qu'ils vous plairont. S'il vous plaît essayez-le et faites-moi savoir si vous trouvez des bugs. Merci pour votre patience!

**Comment by Poyet01** [comment]
Aïe ! J'ai plein d'erreurs :
`ErrorException: filemtime(): stat failed for /home3/geneapoy/public_html/webtrees/modules_v4/argon-webtrees-theme/resources/css/theme.css in /home3/geneapoy/public_html/webtrees/app/Module/ModuleCustomTrait.php:154 Stack trace: #0 [internal function]: Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}() #1 /home3/geneapoy/public_html/webtrees/app/Module/ModuleCustomTrait.php(154): filemtime() #2 /home3/geneapoy/public_html/webtrees/modules_v4/argon-webtrees-theme/module.php(144): Fisharebest\Webtrees\Module\MinimalTheme@anonymous->assetUrl() #3 /home3/geneapoy/public_html/webtrees/modules_v4/argon-webtrees-theme/resources/views/layouts/default.phtml(58): Fisharebest\Webtrees\Module\MinimalTheme@anonymous->stylesheets() #4 /home3/geneapoy/public_html/webtrees/app/View.php(183): include('/home3/geneapoy...') #5 /home3/geneapoy/public_html/webtrees/app/View.php(278): Fisharebest\Webtrees\View->render() #6 /home3/geneapoy/public_html/webtrees/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make() #7 /home3/geneapoy/public_html/webtrees/app/Http/ViewResponseTrait.php(54): view() #8 /home3/geneapoy/public_html/webtrees/app/Http/RequestHandlers/UserPage.php(84): Fisharebest\Webtrees\Http\RequestHandlers\UserPage->viewResponse() #9 /home3/geneapoy/public_html/webtrees/app/Http/Middleware/RequestHandler.php(54): Fisharebest\Webtrees\Http\RequestHandlers\UserPage->handle() #10 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process() #11 /home3/geneapoy/public_html/webtrees/modules_v4/webtrees-reminder/src/Modules/ReminderModule.php(98): Middleland\Dispatcher->handle() #12 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Reminder\Modules\ReminderModule->process() #13 /home3/geneapoy/public_html/webtrees/modules_v4/webtrees-faces/src/Modules/FacesModule.php(94): Middleland\Dispatcher->handle() #14 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Faces\Modules\FacesModule->process() #15 /home3/geneapoy/public_html/webtrees/modules_v4/vesta_research_suggestions/ResearchSuggestionsModule.php(254): Middleland\Dispatcher->handle() #16 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule->process() #17 /home3/geneapoy/public_html/webtrees/app/Module/CheckForNewVersion.php(115): Middleland\Dispatcher->handle() #18 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion->process() #19 /home3/geneapoy/public_html/webtrees/app/Http/Middleware/AuthLoggedIn.php(51): Middleland\Dispatcher->handle() #20 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\AuthLoggedIn->process() #21 /home3/geneapoy/public_html/webtrees/app/Http/Middleware/CheckCsrf.php(80): Middleland\Dispatcher->handle() #22 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process() #23 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle() #24 /home3/geneapoy/public_html/webtrees/app/Webtrees.php(269): Middleland\Dispatcher->dispatch() #25 /home3/geneapoy/public_html/webtrees/app/Http/Middleware/Router.php(153): Fisharebest\Webtrees\Webtrees::dispatch() #26 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process() #27 /home3/geneapoy/public_html/webtrees/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher->handle() #28 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process() #29 /home3/geneapoy/public_html/webtrees/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher->handle() #30 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process() #31 /home3/geneapoy/public_html/webtrees/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher->handle() #32 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process() #33 /home3/geneapoy/public_html/webtrees/app/Http/Middleware/CheckForNewVersion.php(65): Middleland\Dispatcher->handle() #34 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process() #35 /home3/geneapoy/public_html/webtrees/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle() #36 /home3/geneapoy/public_html/webtrees/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}() #37 /home3/geneapoy/public_html/webtrees/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction() #38 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process() #39 /home3/geneapoy/public_html/webtrees/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher->handle() #40 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process() #41 /home3/geneapoy/public_html/webtrees/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher->handle() #42 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process() #43 /home3/geneapoy/public_html/webtrees/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle() #44 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process() #45 /home3/geneapoy/public_html/webtrees/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher->handle() #46 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process() #47 /home3/geneapoy/public_html/webtrees/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle() #48 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process() #49 /home3/geneapoy/public_html/webtrees/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle() #50 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process() #51 /home3/geneapoy/public_html/webtrees/app/Http/Middleware/UseDatabase.php(118): Middleland\Dispatcher->handle() #52 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process() #53 /home3/geneapoy/public_html/webtrees/app/Http/Middleware/BadBotBlocker.php(233): Middleland\Dispatcher->handle() #54 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process() #55 /home3/geneapoy/public_html/webtrees/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle() #56 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process() #57 /home3/geneapoy/public_html/webtrees/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle() #58 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process() #59 /home3/geneapoy/public_html/webtrees/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle() #60 /home3/geneapoy/public_html/webtrees/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process() #61 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process() #62 /home3/geneapoy/public_html/webtrees/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle() #63 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process() #64 /home3/geneapoy/public_html/webtrees/app/Http/Middleware/BaseUrl.php(79): Middleland\Dispatcher->handle() #65 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process() #66 /home3/geneapoy/public_html/webtrees/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle() #67 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process() #68 /home3/geneapoy/public_html/webtrees/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle() #69 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process() #70 /home3/geneapoy/public_html/webtrees/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle() #71 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process() #72 /home3/geneapoy/public_html/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle() #73 /home3/geneapoy/public_html/webtrees/app/Webtrees.php(269): Middleland\Dispatcher->dispatch() #74 /home3/geneapoy/public_html/webtrees/app/Webtrees.php(256): Fisharebest\Webtrees\Webtrees::dispatch() #75 /home3/geneapoy/public_html/webtrees/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest() #76 {main}`

**Comment by jchue** [comment]
Hello, could you please double-check the permissions, particularly on the `resources/css/` directory?

---

Bonjour, pourriez-vous s'il vous plaît revérifier les permissions, en particulier sur le répertoire `resources/css/`?

**Comment by Poyet01** [comment]
Bonjour,
J'ai le même problème en changeant les attributs en 777
---------------------------------------------------------------
Hello,
I have the same problem changing the attributes to 777

**Comment by jchue** [comment]
Can you walk through your installation steps? Did you clone the repository, download `argon-2.0.0.zip`, or download the source code `.zip`/`.tar.gz`?

---

Pouvez-vous parcourir les étapes d'installation ? Avez-vous cloné le référentiel, téléchargé `argon-2.0.0.zip` ou téléchargé le code source `.zip`/`.tar.gz`?

**Comment by Poyet01** [comment]
J'ai téléchargé le code source en .ZIP sous ce même lien, et j'ai bien respecté les différentes étapes de l'installation (dézipper, renommé le dossier, le dépasser sous modules_v4
----------------------------------------------------------------------------------
I downloaded the source code in .ZIP under this same link, and I followed the different installation steps (unzip, rename the folder, go beyond it under modules_v4

**Comment by jchue** [comment]
Ah, that is the issue. The source code does not have the compiled CSS. (The `resources/css/` directory is empty.)

It's preferred to use the `argon-2.0.0.zip` file, which already has everything compiled and minimized.

If you want to use the source code, you will need to run:

```
npm install
npm run dev
```

Then make a change to a `.scss` file in the `src/scss/` directory, because the npm script won't compile until it detects a change.

I should make this clear in the README.

---

Ah, c'est le problème. Le code source n'a pas le CSS compilé. (Le répertoire `resources/css/` est vide.)

Il est préférable d'utiliser le fichier `argon-2.0.0.zip`, qui a déjà tout compilé et minimisé.

Si vous souhaitez utiliser le code source, vous devrez exécuter :

```
npm install
npm run dev
```

Modifiez ensuite un fichier .scss dans le répertoire `src/scss/`, car le script npm ne compilera pas tant qu'il ne détectera pas un changement.

Je devrais le préciser dans le README.

**Comment by Poyet01** [comment]
C'est bon cela fonctionne maintenant.
Merci pour votre aide
---------------------------------
Good it works now.
Thanks for your help

**Comment by jchue** [comment]
Great.
