### ISSUE TITLE
Dropdown arrows don't appear on big screens

### ISSUE THREAD

**Issue by SvbZ3r0** [jchue/argon-webtrees-theme#11]
To be exact, the dropdown arrows tagged `a.nav-link.dropdown-toggle::after` do not show up on screens wider than 991 px.
![image](https://user-images.githubusercontent.com/57280279/173474704-375cfcc2-de8e-4060-bd7e-e799aa1c5434.png)
![image](https://user-images.githubusercontent.com/57280279/173474725-4c02e576-43bb-409d-9529-c7071ffc50b0.png)
Probably has something to do with the `@media` tag:
![image](https://user-images.githubusercontent.com/57280279/173474810-5d91bf0b-400c-4b4d-bbd8-79363dda84e6.png)
I do not know how to fix this, or I would submit a PR myself.
Thanks for the great work.

**Comment by jchue** [comment]
Thanks for the initial investigation! This is very weird. I don't see the issue in Firefox or Chrome, I do see it in Safari, but it looks like you are using Chrome?

**Comment by SvbZ3r0** [comment]
Yes, this is on chrome. But I just tested it on Edge and the issue exists there too.

**Comment by jchue** [comment]
Alright, give me some time to look into it.

**Comment by jchue** [comment]
Root cause: I forgot to import Font Awesome as a dependency. (For some reason, Argon only uses the icon, which is an arrow, in the dropdown menus when width >= 992px. Anything lower uses a triangle, which isn't a Font Awesome icon. Hence the inconsistent behavior.)

This should be fixed by cb46dec901168a352306f7dd31c8b49f5b102003. @SvbZ3r0, could you try the latest release?

**Comment by SvbZ3r0** [comment]
It's fixed now. Thank you!

**Comment by SvbZ3r0** [comment]
Off topic for this issue, but does the theme not work for the admin pages? I don't know if it is a bug or a limitation of scope.

**Comment by jchue** [comment]
By admin pages, do you mean the control panel? Hm, no, it wasn't intended to, and I wasn't aware of any theme that did. All the themes I've ever tried only updated the public-facing pages. Do you know of a theme that updates the admin control panel as well?

**Comment by SvbZ3r0** [comment]
Yes, I mean the control panel. And, no.. I don't know if any other theme does that. I'm extremely new to webtrees, and yours was the first and only theme I tried.
Anyway, if it's not meant to theme the control panel, then it is what it is, I guess. Thanks for your time!

**Comment by jchue** [comment]
No worries!
