### ISSUE TITLE
FEATURE REQUEST: custom css

### ISSUE THREAD

**Issue by JesseWebDotCom** [jchue/argon-webtrees-theme#15]
To be able to customize this theme without touching the module files (ex. I want to change the icon for the individual silhouette), I'd like you to add the ability for a user defined custom.css file.  I was able to get this working as follows:

1. create resources/css/custom.css
2. update module.php stylesheets function as follows:3. 
```
    public function stylesheets(): array
    {
        // NOTE - a future version of webtrees will allow the modules to be stored in a private folder.
        // Only files in the /public/ folder will be accessible via the webserver.
        // Since modules cannot copy their files to the /public/ folder, they need to provide them via a callback.
        $stylesheets[] = $this->assetUrl('css/theme.css');
        $stylesheets[] = $this->assetUrl('css/custom.css');
        $stylesheets[] = $this->assetUrl('css/fontawesome.css');

        return $stylesheets;
    }
```

Then I just add my custom CSS to resources/css/custom.css

**Comment by jchue** [comment]
You can use https://github.com/makitso/custom-css.
