### ISSUE TITLE
Asset type error

### ISSUE THREAD

**Issue by hartenthaler** [jchue/argon-webtrees-theme#16]
When the Argon theme is activated there is an error shown in the browser console
```
Asset?asset=js%2Fscript.js&hash=1654449353:1 
Uncaught TypeError: Cannot read properties of null (reading 'offsetHeight')
    at Asset?asset=js%2Fscript.js&hash=1654449353:1:116
```
Could this error be related to the Argon module?

**Comment by jchue** [comment]
@hartenthaler, is this in the admin Control Panel? What version of webtrees are you using?

**Comment by hartenthaler** [comment]
No, this was on all webtrees pages, even if the Argon module was installed but not used. When Argon was not installed the error disappeared. I'm using webtrees 2.1.7.

With the latest version of your theme module it disappeared. So I'm closing this issue now.
