### ISSUE TITLE
chart-box thumbnail margin change of no effect.

### ISSUE THREAD

**Issue by photon-flip** [jchue/argon-webtrees-theme#18]
views/chart-box.phtml line 5, target for preg_replace is no longer valid in webtrees 2.1
.wt-chart-box-thumbnail float-left mr-1 is now
.wt-chart-box-thumbnail float-start me-1.
Also cannot find .mr-2 in argon css.
Your intended change may have been quite subtle so you probably haven't noticed that it's using the default styling.

**Comment by jchue** [comment]
Ah, thanks, I totally missed this. It looks like they changed the x-axis class names in Bootstrap 5. This should be fixed by f266909a3a668f2dff799240a87dd749a251fb94. Could you try the latest release?
