### ISSUE TITLE
Favourites block

### ISSUE THREAD

**Issue by HRN65** [jchue/argon-webtrees-theme#20]
Thank you for a great theme!
On my home page I'm using the Favourites block, but it appairs the chart-boxes are not defined, thus missing padding and background colors. Could you please take a look at this?

**Comment by jchue** [comment]
Hi @HRN65, could you please show me a screenshot?

**Comment by HRN65** [comment]
I have now activated Argon theme on my site.
You can see it at:
https://visitusinmaputo.com/webtree/tree/familie

**Comment by photon-flip** [comment]
jchue,
Most charts use the  .wt-chart-box-m class
But the Favorites Block uses [dir] .wt-chart-box-m
That just needs to be added to the CSS. 
I'm sure you've got that figured out already.

**Comment by HRN65** [comment]
Thank you photon-flip. 
I just added [dir] .wt-chart-box-m, [dir] .wt-chart-box-m .wt-chart-box-dropdown {background: #f4fdff; padding:2px} [dir] .wt-chart-box-f, [dir] .wt-chart-box-f .wt-chart-box-dropdown {
background: #fff4f9; padding:2px} to CSS

**Comment by HRN65** [comment]
@jchue 
Here is a screenshot showing the Favourites block

![favourites](https://user-images.githubusercontent.com/55854079/206876871-2104f933-1c7f-4f5b-873a-f3c03c9630a1.jpg)

**Comment by jchue** [comment]
Thanks for all the help on this one. It should be fixed by a6cd61254ee174e51810597fa0b278f02ffc2795. Could you try the latest release?

**Comment by jchue** [comment]
Feel free to open a new issue if you find any other problems.
