### ISSUE TITLE
popup position of chartbox menu

### ISSUE THREAD

**Issue by arbor95** [jchue/argon-webtrees-theme#23]
I have no sidebar (checked of "family navigator",..) .
So there is no place for the popup-menues of the right side of the chartboxes. ( clicking on the + or the tree icon)

you can test on https://freris.de with activating argon-theme

**Comment by jchue** [comment]
Hi, the dropdowns should be positioned automatically to be within view. Could you try the latest release and post a screenshot if the issue still persists?

**Comment by arbor95** [comment]
thx, is ok.
