### ISSUE TITLE
development

### ISSUE THREAD

**Issue by Tuetenk0pp** [jchue/argon-webtrees-theme#6]
I just discovered your theme and so far I really like the clean and modern looks of it! I also noticed that the last commit was one year ago...

Unfortunately, the theme doesn't work on some pages. Here's a screenshot:
![Error – webtrees](https://user-images.githubusercontent.com/55783419/113896793-8f66d080-97ca-11eb-8c27-5157d251f1af.jpg)

I'm using the dtjs48jkt/webtrees docker image ver 2.0.15 with a reverse proxy, though I don't really think that this is the issue, because other themes work just fine.

Do you plan on updating the theme? I really really like it. Unfortunately I know absolutely nothing about css, so I don't think that I can be helpful.

**Comment by jchue** [comment]
Hi @Tuetenk0pp, thanks for reporting this issue. As you pointed out, I haven't updated this theme in a while. However, I am starting to work on it again. I'm first doing some housekeeping behind the scenes and improving how the views are customized. I'll take a look at this issue shortly after. Thank you for your patience!

**Comment by Tuetenk0pp** [comment]
No worries! Thanks for your work! I know projects like this take time and again, I really appreciate it.

There's a list of webtrees modules on the official website, where this could be added for more publicity (https://webtrees.net/download/modules).

**Comment by jchue** [comment]
This should be resolved by 255f1a6a9b4fdf1f9180445969b6ad4313cef955. Please use the latest release for your webtrees version! Let me know if you encounter any more issues.

**Comment by Tuetenk0pp** [comment]
> 
> 
> This should be resolved by [255f1a6](https://github.com/jchue/argon-webtrees-theme/commit/255f1a6a9b4fdf1f9180445969b6ad4313cef955). Please use the latest release for your webtrees version! Let me know if you encounter any more issues.

Very nice! Thank you :)

I already tested it with my webtrees instance and it works absolutely fine.
