### ISSUE TITLE
White space when using Argon together with FancyImageBar

### ISSUE THREAD

**Issue by hartenthaler** [jchue/argon-webtrees-theme#8]
When using Argon together with FancyImageBar there is a superfluous white space above the image bar.
![Screenshot (239)_LI](https://user-images.githubusercontent.com/6324175/114049395-b5a07500-988b-11eb-9311-36a215f271d7.jpg)

**Comment by jchue** [comment]
Thanks for reporting this, @hartenthaler. Looking into it now.

**Comment by jchue** [comment]
Fixed by 08951b7a48b33087ce72f96a93eec5861914ccf8
